serenity.project.name=SWAG LABS
serenity.test.root=oren.example
webdriver.driver=firefox
webdriver.autodownload=true
serenity.browser.maximized=true
serenity.use.unique.browser=false
serenity.restart.browser.each.scenario=true
webdriver.timeouts.implicitlywait = 10000
serenity.timeout = 10000
